-- Script generated by Redgate Compare v0.1.5.6119

SET check_function_bodies = false;


DO language plpgsql $$BEGIN RAISE NOTICE 'Creating public.customer.twitter_handle...';END$$;
ALTER TABLE public.customer ADD COLUMN twitter_handle text;
SET check_function_bodies = true;
