-- Script generated by Redgate Compare v0.1.5.6138

SET check_function_bodies = false;


DO language plpgsql $$BEGIN RAISE NOTICE 'Creating public.customer_email...';END$$;
CREATE TABLE public.customer_email (
    customer_id integer NOT NULL,
    email_id integer NOT NULL
);
ALTER TABLE public.customer_email ADD CONSTRAINT customer_email_pkey PRIMARY KEY (customer_id, email_id);


DO language plpgsql $$BEGIN RAISE NOTICE 'Creating public.customer_email.customer_email_customer_id...';END$$;
ALTER TABLE public.customer_email ADD CONSTRAINT customer_email_customer_id FOREIGN KEY (customer_id) REFERENCES public.customer (customer_id);


DO language plpgsql $$BEGIN RAISE NOTICE 'Creating public.email_email_id_seq...';END$$;
CREATE SEQUENCE public.email_email_id_seq
AS bigint
INCREMENT BY 1
MINVALUE 1
MAXVALUE 9223372036854775807
START 1
CACHE 1
NO CYCLE;


DO language plpgsql $$BEGIN RAISE NOTICE 'Creating public.email...';END$$;
CREATE TABLE public.email (
    email_id integer NOT NULL DEFAULT nextval('public.email_email_id_seq'::regclass),
    email_address text NOT NULL
);
ALTER TABLE public.email ADD CONSTRAINT email_pkey PRIMARY KEY (email_id);


DO language plpgsql $$BEGIN RAISE NOTICE 'Creating public.customer_email.customer_email_email_id...';END$$;
ALTER TABLE public.customer_email ADD CONSTRAINT customer_email_email_id FOREIGN KEY (email_id) REFERENCES public.email (email_id);
SET check_function_bodies = true;


insert into email (email_address)
select email from customer;

insert into customer_email (customer_id, email_id)
select customer_id, email_id 
from customer
inner join email on customer.email = email.email_address;


DO language plpgsql $$BEGIN RAISE NOTICE 'Dropping public.customer.email';END$$;
ALTER TABLE public.customer DROP COLUMN email;
